# Project: Improving Disaster Resilience

## Join the common elements of the NOAA and US Census Clusters

### 
### Disaster Resilience Project

### Data Used: NOAA and US Census Clusters for Bartholomew County

Andrew Sommers

### Purpose

- Create an output file of the common counties between the NOAA and US Census cluster that contains Bartholomew County


#### History üóìÔ∏è

   Date | Person | Details
   ---- | ------ | -------
 - 07/31/2023| Andrew Sommers| Create initial notebook
 - 08/25/2023| Andrew Sommers| Update documentation

### Importing Libraries

We start by importing the libraries required for this notebook, adding in the ACS API key, and creating the function `json_to_dataframe` which is the function used in all our notebooks that make a call to the API. This function converts the API response into a dataframe and a readable format.

In [1]:
#import requests # request http, api
import pandas as pd # tabluar data
#from functools import reduce
import numpy as np
import os

import matplotlib.pyplot as plt
plt.style.use('default')
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')


pd.options.display.max_columns = None # show all columns in display
pd.options.display.max_rows = None # show all columns in display

In [2]:
# change the notebooks data source directory to the Disaster Resilience  Directory - change this for your local environment
# set the sourcing directory where the 'Data' folder is located; this is the raw data input files.  
# this notebook assumes data files are located in a 'Data' folder in the following path:
os.chdir('C:\\Users\\andre\\OneDrive\\Documents\\IndianaUniversity\\D592\\Project_Disaster_Resilience\\Data\\NOAA')
NOAA_Cluster = pd.read_csv(f'NOAA_BartholomewCluster_All_Counties.csv', dtype = str, skipinitialspace = True)
NOAA_Cluster.set_index("FIPS", inplace = True)
len(NOAA_Cluster)

1877

In [3]:
NOAA_Cluster.head(3)

,Drought,Dust Storm,Fire and Related Events,Flood and Related Events,Hurricanes and Tropical Storms,Marine Costal and Wave Events,Marine Severe Storms,Severe Storms and Wind,Tornado,Winter Cold and Freezing,Winter Storms,cluster,State,County,Total_Property_Damage
FIPS,,,,,,,,,,,,,,,
0500000US01005,0,0,0,2,1,0,0,3,4,0,0,1,ALABAMA,BARBOUR,555000.0
0500000US01007,0,0,0,3,1,0,0,3,4,0,0,1,ALABAMA,BIBB,14538750.0
0500000US01011,0,0,0,3,1,0,0,2,1,0,0,1,ALABAMA,BULLOCK,300000.0

In [4]:
# change the notebooks data source directory to the Disaster Resilience  Directory - change this for your local environment
# set the sourcing directory where the 'Data' folder is located; this is the raw data input files.  
# this notebook assumes data files are located in a 'Data' folder in the following path:
os.chdir('C:\\Users\\andre\\OneDrive\\Documents\\IndianaUniversity\\D592\\Project_Disaster_Resilience\\Data\\usCensus')
usCensus_Cluster = pd.read_csv(f'US_Census_BartholomewCluster_All_Counties.csv', dtype = str, skipinitialspace = True)
usCensus_Cluster.set_index("FIPS", inplace = True)
len(usCensus_Cluster)

607

In [5]:
usCensus_Cluster.head(3)

,POPULATION,POP_DENSITY,PCT_URBAN,MEDIAN_INCOME,cluster,State,County
FIPS,,,,,,,
0500000US01001,58239,91.8,0.59,31338.0,11,ALABAMA,AUTAUGA
0500000US01009,58884,88.9,0.093,23818.0,11,ALABAMA,BLOUNT
0500000US01021,44857,63.0,0.149,27986.0,11,ALABAMA,CHILTON

In [6]:
joined_Cluster = NOAA_Cluster.join(usCensus_Cluster, how = 'inner', lsuffix="_left", sort = False)
joined_Cluster.sort_values(['POPULATION', 'POP_DENSITY'], inplace = True)
len(joined_Cluster)

297

In [8]:
joined_Cluster.head(3)

,Drought,Dust Storm,Fire and Related Events,Flood and Related Events,Hurricanes and Tropical Storms,Marine Costal and Wave Events,Marine Severe Storms,Severe Storms and Wind,Tornado,Winter Cold and Freezing,Winter Storms,cluster_left,State_left,County_left,Total_Property_Damage,POPULATION,POP_DENSITY,PCT_URBAN,MEDIAN_INCOME,cluster,State,County
FIPS,,,,,,,,,,,,,,,,,,,,,,
0500000US12055,0,0,0,2,7,0,0,13,3,0,0,1,FLORIDA,HIGHLANDS,361924500.0,101174,97.2,0.8,27830.0,11,FLORIDA,HIGHLANDS
0500000US37049,0,0,0,3,10,2,0,3,2,0,0,1,NORTH CAROLINA,CRAVEN,55150000.0,101405,146.0,0.648,31596.0,11,NORTH CAROLINA,CRAVEN
0500000US51073,0,0,1,0,4,4,0,2,6,0,1,1,VIRGINIA,GLOUCESTER,11852800.0,38586,169.2,0.284,43072.0,11,VIRGINIA,GLOUCESTER

In [9]:
# output all US counties to a csv file
os.chdir('C:\\Users\\andre\\OneDrive\\Documents\\IndianaUniversity\\D592\\Project_Disaster_Resilience\\Data\\Clusters')
joined_Cluster.reset_index(inplace=True)
joined_Cluster = joined_Cluster.rename(columns = {'index':'FIPS'})
joined_Cluster.to_csv(f'joinedClusters_BartholomewCounty_All_Counties.csv', header=True, index=False)
print('end of cluster inner join and save function', len(joined_Cluster))

end of cluster inner join and save function 297

In [10]:
# output Indiana counties to a csv file
df1 = joined_Cluster[joined_Cluster['State'] == 'INDIANA']
os.chdir('C:\\Users\\andre\\OneDrive\\Documents\\IndianaUniversity\\D592\\Project_Disaster_Resilience\\Data\\Clusters')
df1.reset_index(inplace=True)
df1 = df1.rename(columns = {'index':'FIPS'})
df1.to_csv(f'joinedClusters_BartholomewCounty_Indiana_Counties.csv', header=True, index=False)
print('end of cluster inner join and save function', len(df1))

end of cluster inner join and save function 15